apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
   name: data-capture-service-cert-uat
   namespace: claim-criminal-injuries-compensation-uat
  spec:
   secretName: data-capture-service-cert-secret-uat
   issuerRef:
      name: cica-uat
      kind: ClusterIssuer
   commonName: 'data-capture-service.uat.claim-criminal-injuries-compensation.service.justice.gov.uk'
   acme:
     config:
     - domains:
       - 'data-capture-service.uat.claim-criminal-injuries-compensation.service.justice.gov.uk'
       dns01:
         provider: route53-cloud-platform
