kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
 name: circleci
 namespace: claim-criminal-injuries-compensation-uat
rules:
 - apiGroups:
     - ""
   resources:
     - "pods/portforward"
     - "secrets"
     - "services"
     - "pods"
   verbs:
     - "patch"
     - "get"
     - "create"
     - "delete"
     - "list"
 - apiGroups:
     - "extensions"
   resources:
     - "deployments"
     - "ingresses"
   verbs:
     - "get"
     - "update"
     - "delete"
     - "create"
     - "patch"
 - apiGroups:
      - "certmanager.k8s.io"
   resources:
      - "certificates"
   verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"