apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dcs-app-uat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dcs-app-uat
    spec:
      containers:
      - name: data-capture-service 
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/cica/cica-repo-uat:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3100
        env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: data-capture-service
              key: secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: dcsjs
              key: url
        - name: DCS_LOG_LEVEL
          value: "info"
        - name: MESSAGE_BUS_SERVICE
          valueFrom:
            secretKeyRef:
              name: message-bus-url
              key: url
        - name: MB_AUTH
          valueFrom:
            secretKeyRef:
              name: message-bus-url
              key: url