apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 213.107.167.128/32
    external-dns.alpha.kubernetes.io/set-identifier: dcs-ingress-uat-claim-criminal-injuries-compensation-uat-green
    external-dns.alpha.kubernetes.io/aws-weight: '100'
  name: dcs-ingress-uat
  namespace: claim-criminal-injuries-compensation-uat
spec:
  tls:
    - hosts:
        - data-capture-service.uat.claim-criminal-injuries-compensation.apps.live.cloud-platform.service.justice.gov.uk
    - hosts:
        - data-capture-service.uat.claim-criminal-injuries-compensation.service.justice.gov.uk
      secretName: data-capture-service-cert-secret-uat
  ingressClassName: default
  rules:
    - host: data-capture-service.uat.claim-criminal-injuries-compensation.apps.live.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            backend:
              service:
                name: dcs-service-uat
                port:
                  number: 80
            pathType: ImplementationSpecific
    - host: data-capture-service.uat.claim-criminal-injuries-compensation.service.justice.gov.uk
      http:
        paths:
          - path: /
            backend:
              service:
                name: dcs-service-uat
                port:
                  number: 80
            pathType: ImplementationSpecific
