kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: claim-criminal-injuries-compensation-dev
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: claim-criminal-injuries-compensation-dev
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io